`ifndef SOFTMAX_CFG_SVH
`define SOFTMAX_CFG_SVH

`ifndef SOFTMAX_DATA_WIDTH
`define SOFTMAX_DATA_WIDTH 32
`endif

`ifndef SOFTMAX_FRACTIONAL_BITS
`define SOFTMAX_FRACTIONAL_BITS 16
`endif

`ifndef SOFTMAX_NUM_ELEMENTS
`define SOFTMAX_NUM_ELEMENTS 8
`endif

`ifndef SOFTMAX_INPUT_MIN_INTEGER
`define SOFTMAX_INPUT_MIN_INTEGER -4
`endif

`ifndef SOFTMAX_INPUT_MAX_INTEGER
`define SOFTMAX_INPUT_MAX_INTEGER 4
`endif

`ifndef SOFTMAX_TOLERANCE_LSB
`define SOFTMAX_TOLERANCE_LSB 66
`endif

`ifndef SOFTMAX_RANDOM_TRANSACTION_COUNT
`define SOFTMAX_RANDOM_TRANSACTION_COUNT 200
`endif

`ifndef SOFTMAX_RESET_TRAFFIC_COUNT
`define SOFTMAX_RESET_TRAFFIC_COUNT 16
`endif

`ifndef SOFTMAX_TEST_TIMEOUT_CYCLES
`define SOFTMAX_TEST_TIMEOUT_CYCLES 5000
`endif

`ifndef SOFTMAX_DRAIN_QUIET_CYCLES
`define SOFTMAX_DRAIN_QUIET_CYCLES 32
`endif

`ifndef SOFTMAX_EXPECTED_LATENCY_CYCLES
`define SOFTMAX_EXPECTED_LATENCY_CYCLES (21 + 2 * $clog2(NUM_ELEMENTS))
`endif

`ifndef SOFTMAX_CLOCK_PERIOD
`define SOFTMAX_CLOCK_PERIOD 10ns
`endif

`endif
